# permissions for end users to edit mms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mm-editor-role
rules:
- apiGroups:
  - mysql.operator.swxlbjs.com
  resources:
  - mms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mysql.operator.swxlbjs.com
  resources:
  - mms/status
  verbs:
  - get
