# permissions for end users to view mms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mm-viewer-role
rules:
- apiGroups:
  - mysql.operator.swxlbjs.com
  resources:
  - mms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mysql.operator.swxlbjs.com
  resources:
  - mms/status
  verbs:
  - get
